/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { PrismaService } from "nestjs-prisma";
import {
  Prisma,
  PublicationsOnCommunity,
  Publication,
  Community,
} from "@prisma/client";
import { PaginatedInterface } from "../../util/PaginatedInterface";
import { DbService } from "src/dbService/db.service";

export class PublicationsOnCommunityServiceBase {
  constructor(protected readonly prisma: DbService) {}

  async count<T extends Prisma.PublicationsOnCommunityFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.PublicationsOnCommunityFindManyArgs>
  ): Promise<number> {
    return this.prisma.publicationsOnCommunity.count(args);
  }

  async findMany<T extends Prisma.PublicationsOnCommunityFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.PublicationsOnCommunityFindManyArgs>
  ): Promise<PaginatedInterface<PublicationsOnCommunity>> {
    const [data, totalCount] = await Promise.all([
      this.prisma.publicationsOnCommunity.findMany(args),
      this.prisma.publicationsOnCommunity.count(),
    ]);

    return { paginatedResult: data, totalCount };
  }
  async findOne<T extends Prisma.PublicationsOnCommunityFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.PublicationsOnCommunityFindUniqueArgs>
  ): Promise<PublicationsOnCommunity | null> {
    return this.prisma.publicationsOnCommunity.findUnique(args);
  }
  async create<T extends Prisma.PublicationsOnCommunityCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.PublicationsOnCommunityCreateArgs>
  ): Promise<PublicationsOnCommunity> {
    return this.prisma.publicationsOnCommunity.create<T>(args);
  }
  async update<T extends Prisma.PublicationsOnCommunityUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.PublicationsOnCommunityUpdateArgs>
  ): Promise<PublicationsOnCommunity> {
    return this.prisma.publicationsOnCommunity.update<T>(args);
  }
  async delete<T extends Prisma.PublicationsOnCommunityDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.PublicationsOnCommunityDeleteArgs>
  ): Promise<PublicationsOnCommunity> {
    return this.prisma.publicationsOnCommunity.delete(args);
  }

  async getPublication(parentId: string): Promise<Publication | null> {
    return this.prisma.publicationsOnCommunity
      .findUnique({
        where: { id: parentId },
      })
      .publication();
  }

  async getCommunity(parentId: string): Promise<Community | null> {
    return this.prisma.publicationsOnCommunity
      .findUnique({
        where: { id: parentId },
      })
      .community();
  }
}
