/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { PublicationsOnCommunityWhereInput } from "./PublicationsOnCommunityWhereInput";
import { Type } from "class-transformer";
import { PublicationsOnCommunityOrderByInput } from "./PublicationsOnCommunityOrderByInput";

@ArgsType()
class PublicationsOnCommunityFindManyArgs {
  @ApiProperty({
    required: false,
    type: () => PublicationsOnCommunityWhereInput,
  })
  @Field(() => PublicationsOnCommunityWhereInput, { nullable: true })
  @Type(() => PublicationsOnCommunityWhereInput)
  where?: PublicationsOnCommunityWhereInput;

  @ApiProperty({
    required: false,
    type: PublicationsOnCommunityOrderByInput,
  })
  @Field(() => PublicationsOnCommunityOrderByInput, { nullable: true })
  @Type(() => PublicationsOnCommunityOrderByInput)
  orderBy?: PublicationsOnCommunityOrderByInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { PublicationsOnCommunityFindManyArgs };
