/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { PaginatedInterface } from "../../util/PaginatedInterface";
import { CreatePublicationsOnCommunityArgs } from "./CreatePublicationsOnCommunityArgs";
import { UpdatePublicationsOnCommunityArgs } from "./UpdatePublicationsOnCommunityArgs";
import { DeletePublicationsOnCommunityArgs } from "./DeletePublicationsOnCommunityArgs";
import { PublicationsOnCommunityFindManyArgs } from "./PublicationsOnCommunityFindManyArgs";
import { PublicationsOnCommunityFindUniqueArgs } from "./PublicationsOnCommunityFindUniqueArgs";
import { PublicationsOnCommunity } from "./PublicationsOnCommunity";
import { Publication } from "../../publication/base/Publication";
import { Community } from "../../community/base/Community";
import { PublicationsOnCommunityService } from "../publicationsOnCommunity.service";

@graphql.Resolver(() => PublicationsOnCommunity)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class PublicationsOnCommunityResolverBase {
  constructor(
    protected readonly service: PublicationsOnCommunityService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "PublicationsOnCommunity",
    action: "read",
    possession: "any",
  })
  async _publicationsOnCommunitiesMeta(
    @graphql.Args() args: PublicationsOnCommunityFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [PublicationsOnCommunity])
  @nestAccessControl.UseRoles({
    resource: "PublicationsOnCommunity",
    action: "read",
    possession: "any",
  })
  async publicationsOnCommunities(
    @graphql.Args() args: PublicationsOnCommunityFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<PaginatedInterface<PublicationsOnCommunity>> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "PublicationsOnCommunity",
    });
    const results = await this.service.findMany(args);
    const result = results.paginatedResult.map(
      (result: PublicationsOnCommunity) => permission.filter(result)
    );
    return { paginatedResult: result, totalCount: results.totalCount };
  }

  @graphql.Query(() => PublicationsOnCommunity, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "PublicationsOnCommunity",
    action: "read",
    possession: "own",
  })
  async publicationsOnCommunity(
    @graphql.Args() args: PublicationsOnCommunityFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<PublicationsOnCommunity | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "PublicationsOnCommunity",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => PublicationsOnCommunity)
  @nestAccessControl.UseRoles({
    resource: "PublicationsOnCommunity",
    action: "create",
    possession: "any",
  })
  async createPublicationsOnCommunity(
    @graphql.Args() args: CreatePublicationsOnCommunityArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<PublicationsOnCommunity> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "PublicationsOnCommunity",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"PublicationsOnCommunity"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        publication: args.data.publication
          ? {
              connect: args.data.publication,
            }
          : undefined,

        community: args.data.community
          ? {
              connect: args.data.community,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => PublicationsOnCommunity)
  @nestAccessControl.UseRoles({
    resource: "PublicationsOnCommunity",
    action: "update",
    possession: "any",
  })
  async updatePublicationsOnCommunity(
    @graphql.Args() args: UpdatePublicationsOnCommunityArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<PublicationsOnCommunity | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "PublicationsOnCommunity",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"PublicationsOnCommunity"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          publication: args.data.publication
            ? {
                connect: args.data.publication,
              }
            : undefined,

          community: args.data.community
            ? {
                connect: args.data.community,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => PublicationsOnCommunity)
  @nestAccessControl.UseRoles({
    resource: "PublicationsOnCommunity",
    action: "delete",
    possession: "any",
  })
  async deletePublicationsOnCommunity(
    @graphql.Args() args: DeletePublicationsOnCommunityArgs
  ): Promise<PublicationsOnCommunity | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Publication, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "PublicationsOnCommunity",
    action: "read",
    possession: "any",
  })
  async publication(
    @graphql.Parent() parent: PublicationsOnCommunity,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Publication | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Publication",
    });
    const result = await this.service.getPublication(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.ResolveField(() => Community, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "PublicationsOnCommunity",
    action: "read",
    possession: "any",
  })
  async community(
    @graphql.Parent() parent: PublicationsOnCommunity,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Community | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Community",
    });
    const result = await this.service.getCommunity(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
