/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestMorgan from "nest-morgan";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { PaginatedInterface } from "../../util/PaginatedInterface";
import { EntreprisesOnCommunityService } from "../entreprisesOnCommunity.service";
import { EntreprisesOnCommunityCreateInput } from "./EntreprisesOnCommunityCreateInput";
import { EntreprisesOnCommunityWhereInput } from "./EntreprisesOnCommunityWhereInput";
import { EntreprisesOnCommunityWhereUniqueInput } from "./EntreprisesOnCommunityWhereUniqueInput";
import { EntreprisesOnCommunityFindManyArgs } from "./EntreprisesOnCommunityFindManyArgs";
import { EntreprisesOnCommunityUpdateInput } from "./EntreprisesOnCommunityUpdateInput";
import { EntreprisesOnCommunity } from "./EntreprisesOnCommunity";
import { Post } from "../../post/base/Post";
import { getListEntreprisesOnCommunityDto } from "./getListEntreprisesOnCommunity.dto";
@swagger.ApiBearerAuth()
export class EntreprisesOnCommunityControllerBase {
  constructor(
    protected readonly service: EntreprisesOnCommunityService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Post()
  @nestAccessControl.UseRoles({
    resource: "EntreprisesOnCommunity",
    action: "create",
    possession: "any",
  })
  @swagger.ApiCreatedResponse({ type: EntreprisesOnCommunity })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: EntreprisesOnCommunityCreateInput,
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<EntreprisesOnCommunity> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "EntreprisesOnCommunity",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new errors.ForbiddenException(
        `providing the properties: ${properties} on ${"EntreprisesOnCommunity"} creation is forbidden for roles: ${roles}`
      );
    }
    return await this.service.create({
      data: {
        ...data,

        entreprise: data.entreprise
          ? {
              connect: data.entreprise,
            }
          : undefined,

        community: data.community
          ? {
              connect: data.community,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,

        entreprise: {
          select: {
            id: true,
          },
        },

        community: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Get()
  @nestAccessControl.UseRoles({
    resource: "EntreprisesOnCommunity",
    action: "read",
    possession: "any",
  })
  @swagger.ApiOkResponse({ type: getListEntreprisesOnCommunityDto })
  @swagger.ApiForbiddenResponse()
  @swagger.ApiQuery({
    type: () => EntreprisesOnCommunityFindManyArgs,
    style: "deepObject",
    explode: true,
  })
  async findMany(
    @common.Req() request: Request,
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<PaginatedInterface<EntreprisesOnCommunity>> {
    const args = plainToClass(
      EntreprisesOnCommunityFindManyArgs,
      request.query
    );

    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "EntreprisesOnCommunity",
    });
    const results = await this.service.findMany({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,

        entreprise: {
          select: {
            id: true,
          },
        },

        community: {
          select: {
            id: true,
          },
        },
      },
    });
    const result = results.paginatedResult.map(
      (result: EntreprisesOnCommunity) => permission.filter(result)
    );
    return { paginatedResult: result, totalCount: results.totalCount };
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Get("/:id")
  @nestAccessControl.UseRoles({
    resource: "EntreprisesOnCommunity",
    action: "read",
    possession: "own",
  })
  @swagger.ApiOkResponse({ type: EntreprisesOnCommunity })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: EntreprisesOnCommunityWhereUniqueInput,
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<EntreprisesOnCommunity | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "EntreprisesOnCommunity",
    });
    const result = await this.service.findOne({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,

        entreprise: {
          select: {
            id: true,
          },
        },

        community: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return permission.filter(result);
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Patch("/:id")
  @nestAccessControl.UseRoles({
    resource: "EntreprisesOnCommunity",
    action: "update",
    possession: "any",
  })
  @swagger.ApiOkResponse({ type: EntreprisesOnCommunity })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: EntreprisesOnCommunityWhereUniqueInput,
    @common.Body()
    data: EntreprisesOnCommunityUpdateInput,
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<EntreprisesOnCommunity | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "EntreprisesOnCommunity",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new errors.ForbiddenException(
        `providing the properties: ${properties} on ${"EntreprisesOnCommunity"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          entreprise: data.entreprise
            ? {
                connect: data.entreprise,
              }
            : undefined,

          community: data.community
            ? {
                connect: data.community,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,

          entreprise: {
            select: {
              id: true,
            },
          },

          community: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Delete("/:id")
  @nestAccessControl.UseRoles({
    resource: "EntreprisesOnCommunity",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiOkResponse({ type: EntreprisesOnCommunity })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: EntreprisesOnCommunityWhereUniqueInput
  ): Promise<EntreprisesOnCommunity | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,

          entreprise: {
            select: {
              id: true,
            },
          },

          community: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
