/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ChatroomWhereInput } from "./ChatroomWhereInput";
import { Type } from "class-transformer";
import { ChatroomOrderByInput } from "./ChatroomOrderByInput";

@ArgsType()
class ChatroomFindManyArgs {
  @ApiProperty({
    required: false,
    type: () => ChatroomWhereInput,
  })
  @Field(() => ChatroomWhereInput, { nullable: true })
  @Type(() => ChatroomWhereInput)
  where?: ChatroomWhereInput;

  @ApiProperty({
    required: false,
    type: ChatroomOrderByInput,
  })
  @Field(() => ChatroomOrderByInput, { nullable: true })
  @Type(() => ChatroomOrderByInput)
  orderBy?: ChatroomOrderByInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { ChatroomFindManyArgs };
