/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { PaginatedInterface } from "../../util/PaginatedInterface";
import { CreateUsersOnEntrepriseArgs } from "./CreateUsersOnEntrepriseArgs";
import { UpdateUsersOnEntrepriseArgs } from "./UpdateUsersOnEntrepriseArgs";
import { DeleteUsersOnEntrepriseArgs } from "./DeleteUsersOnEntrepriseArgs";
import { UsersOnEntrepriseFindManyArgs } from "./UsersOnEntrepriseFindManyArgs";
import { UsersOnEntrepriseFindUniqueArgs } from "./UsersOnEntrepriseFindUniqueArgs";
import { UsersOnEntreprise } from "./UsersOnEntreprise";
import { Entreprise } from "../../entreprise/base/Entreprise";
import { User } from "../../user/base/User";
import { UsersOnEntrepriseService } from "../usersOnEntreprise.service";

@graphql.Resolver(() => UsersOnEntreprise)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class UsersOnEntrepriseResolverBase {
  constructor(
    protected readonly service: UsersOnEntrepriseService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "UsersOnEntreprise",
    action: "read",
    possession: "any",
  })
  async _usersOnEntreprisesMeta(
    @graphql.Args() args: UsersOnEntrepriseFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [UsersOnEntreprise])
  @nestAccessControl.UseRoles({
    resource: "UsersOnEntreprise",
    action: "read",
    possession: "any",
  })
  async usersOnEntreprises(
    @graphql.Args() args: UsersOnEntrepriseFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<PaginatedInterface<UsersOnEntreprise>> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "UsersOnEntreprise",
    });
    const results = await this.service.findMany(args);
    const result = results.paginatedResult.map((result: UsersOnEntreprise) =>
      permission.filter(result)
    );
    return { paginatedResult: result, totalCount: results.totalCount };
  }

  @graphql.Query(() => UsersOnEntreprise, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "UsersOnEntreprise",
    action: "read",
    possession: "own",
  })
  async usersOnEntreprise(
    @graphql.Args() args: UsersOnEntrepriseFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<UsersOnEntreprise | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "UsersOnEntreprise",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => UsersOnEntreprise)
  @nestAccessControl.UseRoles({
    resource: "UsersOnEntreprise",
    action: "create",
    possession: "any",
  })
  async createUsersOnEntreprise(
    @graphql.Args() args: CreateUsersOnEntrepriseArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<UsersOnEntreprise> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "UsersOnEntreprise",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"UsersOnEntreprise"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        entreprise: args.data.entreprise
          ? {
              connect: args.data.entreprise,
            }
          : undefined,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => UsersOnEntreprise)
  @nestAccessControl.UseRoles({
    resource: "UsersOnEntreprise",
    action: "update",
    possession: "any",
  })
  async updateUsersOnEntreprise(
    @graphql.Args() args: UpdateUsersOnEntrepriseArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<UsersOnEntreprise | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "UsersOnEntreprise",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"UsersOnEntreprise"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          entreprise: args.data.entreprise
            ? {
                connect: args.data.entreprise,
              }
            : undefined,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => UsersOnEntreprise)
  @nestAccessControl.UseRoles({
    resource: "UsersOnEntreprise",
    action: "delete",
    possession: "any",
  })
  async deleteUsersOnEntreprise(
    @graphql.Args() args: DeleteUsersOnEntrepriseArgs
  ): Promise<UsersOnEntreprise | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Entreprise, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "UsersOnEntreprise",
    action: "read",
    possession: "any",
  })
  async entreprise(
    @graphql.Parent() parent: UsersOnEntreprise,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Entreprise | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Entreprise",
    });
    const result = await this.service.getEntreprise(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.ResolveField(() => User, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "UsersOnEntreprise",
    action: "read",
    possession: "any",
  })
  async user(
    @graphql.Parent() parent: UsersOnEntreprise,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<User | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "User",
    });
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
