/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { PrismaService } from "nestjs-prisma";
import { Prisma, OffersOnCommunity, Offer, Community } from "@prisma/client";
import { PaginatedInterface } from "../../util/PaginatedInterface";
import { DbService } from "src/dbService/db.service";

export class OffersOnCommunityServiceBase {
  constructor(protected readonly prisma: DbService) {}

  async count<T extends Prisma.OffersOnCommunityFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.OffersOnCommunityFindManyArgs>
  ): Promise<number> {
    return this.prisma.offersOnCommunity.count(args);
  }

  async findMany<T extends Prisma.OffersOnCommunityFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.OffersOnCommunityFindManyArgs>
  ): Promise<PaginatedInterface<OffersOnCommunity>> {
    const [data, totalCount] = await Promise.all([
      this.prisma.offersOnCommunity.findMany(args),
      this.prisma.offersOnCommunity.count(),
    ]);

    return { paginatedResult: data, totalCount };
  }
  async findOne<T extends Prisma.OffersOnCommunityFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.OffersOnCommunityFindUniqueArgs>
  ): Promise<OffersOnCommunity | null> {
    return this.prisma.offersOnCommunity.findUnique(args);
  }
  async create<T extends Prisma.OffersOnCommunityCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.OffersOnCommunityCreateArgs>
  ): Promise<OffersOnCommunity> {
    return this.prisma.offersOnCommunity.create<T>(args);
  }
  async update<T extends Prisma.OffersOnCommunityUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.OffersOnCommunityUpdateArgs>
  ): Promise<OffersOnCommunity> {
    return this.prisma.offersOnCommunity.update<T>(args);
  }
  async delete<T extends Prisma.OffersOnCommunityDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.OffersOnCommunityDeleteArgs>
  ): Promise<OffersOnCommunity> {
    return this.prisma.offersOnCommunity.delete(args);
  }

  async getOffer(parentId: string): Promise<Offer | null> {
    return this.prisma.offersOnCommunity
      .findUnique({
        where: { id: parentId },
      })
      .offer();
  }

  async getCommunity(parentId: string): Promise<Community | null> {
    return this.prisma.offersOnCommunity
      .findUnique({
        where: { id: parentId },
      })
      .community();
  }
}
