/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { PaginatedInterface } from "../../util/PaginatedInterface";
import { CreateFollowEntrepriseArgs } from "./CreateFollowEntrepriseArgs";
import { UpdateFollowEntrepriseArgs } from "./UpdateFollowEntrepriseArgs";
import { DeleteFollowEntrepriseArgs } from "./DeleteFollowEntrepriseArgs";
import { FollowEntrepriseFindManyArgs } from "./FollowEntrepriseFindManyArgs";
import { FollowEntrepriseFindUniqueArgs } from "./FollowEntrepriseFindUniqueArgs";
import { FollowEntreprise } from "./FollowEntreprise";
import { Entreprise } from "../../entreprise/base/Entreprise";
import { Candidate } from "../../candidate/base/Candidate";
import { FollowEntrepriseService } from "../followEntreprise.service";

@graphql.Resolver(() => FollowEntreprise)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class FollowEntrepriseResolverBase {
  constructor(
    protected readonly service: FollowEntrepriseService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "FollowEntreprise",
    action: "read",
    possession: "any",
  })
  async _followEntreprisesMeta(
    @graphql.Args() args: FollowEntrepriseFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [FollowEntreprise])
  @nestAccessControl.UseRoles({
    resource: "FollowEntreprise",
    action: "read",
    possession: "any",
  })
  async followEntreprises(
    @graphql.Args() args: FollowEntrepriseFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<PaginatedInterface<FollowEntreprise>> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "FollowEntreprise",
    });
    const results = await this.service.findMany(args);
    const result = results.paginatedResult.map((result: FollowEntreprise) =>
      permission.filter(result)
    );
    return { paginatedResult: result, totalCount: results.totalCount };
  }

  @graphql.Query(() => FollowEntreprise, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "FollowEntreprise",
    action: "read",
    possession: "own",
  })
  async followEntreprise(
    @graphql.Args() args: FollowEntrepriseFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<FollowEntreprise | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "FollowEntreprise",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => FollowEntreprise)
  @nestAccessControl.UseRoles({
    resource: "FollowEntreprise",
    action: "create",
    possession: "any",
  })
  async createFollowEntreprise(
    @graphql.Args() args: CreateFollowEntrepriseArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<FollowEntreprise> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "FollowEntreprise",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"FollowEntreprise"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        entreprise: args.data.entreprise
          ? {
              connect: args.data.entreprise,
            }
          : undefined,

        candidate: args.data.candidate
          ? {
              connect: args.data.candidate,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => FollowEntreprise)
  @nestAccessControl.UseRoles({
    resource: "FollowEntreprise",
    action: "update",
    possession: "any",
  })
  async updateFollowEntreprise(
    @graphql.Args() args: UpdateFollowEntrepriseArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<FollowEntreprise | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "FollowEntreprise",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"FollowEntreprise"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          entreprise: args.data.entreprise
            ? {
                connect: args.data.entreprise,
              }
            : undefined,

          candidate: args.data.candidate
            ? {
                connect: args.data.candidate,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => FollowEntreprise)
  @nestAccessControl.UseRoles({
    resource: "FollowEntreprise",
    action: "delete",
    possession: "any",
  })
  async deleteFollowEntreprise(
    @graphql.Args() args: DeleteFollowEntrepriseArgs
  ): Promise<FollowEntreprise | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Entreprise, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "FollowEntreprise",
    action: "read",
    possession: "any",
  })
  async entreprise(
    @graphql.Parent() parent: FollowEntreprise,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Entreprise | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Entreprise",
    });
    const result = await this.service.getEntreprise(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.ResolveField(() => Candidate, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "FollowEntreprise",
    action: "read",
    possession: "any",
  })
  async candidate(
    @graphql.Parent() parent: FollowEntreprise,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Candidate | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Candidate",
    });
    const result = await this.service.getCandidate(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
