/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { PrismaService } from "nestjs-prisma";
import { Prisma, Story, Publication } from "@prisma/client";
import { PaginatedInterface } from "../../util/PaginatedInterface";
import { DbService } from "src/dbService/db.service";

export class StoryServiceBase {
  constructor(protected readonly prisma: DbService) {}

  async count<T extends Prisma.StoryFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.StoryFindManyArgs>
  ): Promise<number> {
    return this.prisma.story.count(args);
  }

  async findMany<T extends Prisma.StoryFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.StoryFindManyArgs>
  ): Promise<PaginatedInterface<Story>> {
    const [data, totalCount] = await Promise.all([
      this.prisma.story.findMany(args),
      this.prisma.story.count(),
    ]);

    return { paginatedResult: data, totalCount };
  }
  async findOne<T extends Prisma.StoryFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.StoryFindUniqueArgs>
  ): Promise<Story | null> {
    return this.prisma.story.findUnique(args);
  }
  async create<T extends Prisma.StoryCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.StoryCreateArgs>
  ): Promise<Story> {
    return this.prisma.story.create<T>(args);
  }
  async update<T extends Prisma.StoryUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.StoryUpdateArgs>
  ): Promise<Story> {
    return this.prisma.story.update<T>(args);
  }
  async delete<T extends Prisma.StoryDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.StoryDeleteArgs>
  ): Promise<Story> {
    return this.prisma.story.delete(args);
  }

  async getPublication(parentId: string): Promise<Publication | null> {
    return this.prisma.story
      .findUnique({
        where: { id: parentId },
      })
      .publication();
  }
}
