/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested } from "class-validator";
import { ChatWhereUniqueInput } from "../../chat/base/ChatWhereUniqueInput";
import { Type } from "class-transformer";
@InputType()
class MessageCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  contenu?: string | null;

  @ApiProperty({
    required: false,
    type: () => ChatWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ChatWhereUniqueInput)
  @IsOptional()
  @Field(() => ChatWhereUniqueInput, {
    nullable: true,
  })
  chat?: ChatWhereUniqueInput | null;
}
export { MessageCreateInput };
