/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { EntrepriseWhereInput } from "./EntrepriseWhereInput";
import { Type } from "class-transformer";
import { EntrepriseOrderByInput } from "./EntrepriseOrderByInput";

@ArgsType()
class EntrepriseFindManyArgs {
  @ApiProperty({
    required: false,
    type: () => EntrepriseWhereInput,
  })
  @Field(() => EntrepriseWhereInput, { nullable: true })
  @Type(() => EntrepriseWhereInput)
  where?: EntrepriseWhereInput;

  @ApiProperty({
    required: false,
    type: EntrepriseOrderByInput,
  })
  @Field(() => EntrepriseOrderByInput, { nullable: true })
  @Type(() => EntrepriseOrderByInput)
  orderBy?: EntrepriseOrderByInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { EntrepriseFindManyArgs };
