/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { PrismaService } from "nestjs-prisma";
import { Prisma, UsersSkill, Skill, User } from "@prisma/client";
import { PaginatedInterface } from "../../util/PaginatedInterface";
import { DbService } from "src/dbService/db.service";

export class UsersSkillServiceBase {
  constructor(protected readonly prisma: DbService) {}

  async count<T extends Prisma.UsersSkillFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.UsersSkillFindManyArgs>
  ): Promise<number> {
    return this.prisma.usersSkill.count(args);
  }

  async findMany<T extends Prisma.UsersSkillFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.UsersSkillFindManyArgs>
  ): Promise<PaginatedInterface<UsersSkill>> {
    const [data, totalCount] = await Promise.all([
      this.prisma.usersSkill.findMany(args),
      this.prisma.usersSkill.count(),
    ]);

    return { paginatedResult: data, totalCount };
  }
  async findOne<T extends Prisma.UsersSkillFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.UsersSkillFindUniqueArgs>
  ): Promise<UsersSkill | null> {
    return this.prisma.usersSkill.findUnique(args);
  }
  async create<T extends Prisma.UsersSkillCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.UsersSkillCreateArgs>
  ): Promise<UsersSkill> {
    return this.prisma.usersSkill.create<T>(args);
  }
  async update<T extends Prisma.UsersSkillUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.UsersSkillUpdateArgs>
  ): Promise<UsersSkill> {
    return this.prisma.usersSkill.update<T>(args);
  }
  async delete<T extends Prisma.UsersSkillDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.UsersSkillDeleteArgs>
  ): Promise<UsersSkill> {
    return this.prisma.usersSkill.delete(args);
  }

  async getSkill(parentId: string): Promise<Skill | null> {
    return this.prisma.usersSkill
      .findUnique({
        where: { id: parentId },
      })
      .skill();
  }

  async getUser(parentId: string): Promise<User | null> {
    return this.prisma.usersSkill
      .findUnique({
        where: { id: parentId },
      })
      .user();
  }
}
