/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { PaginatedInterface } from "../../util/PaginatedInterface";
import { CreateUsersSkillArgs } from "./CreateUsersSkillArgs";
import { UpdateUsersSkillArgs } from "./UpdateUsersSkillArgs";
import { DeleteUsersSkillArgs } from "./DeleteUsersSkillArgs";
import { UsersSkillFindManyArgs } from "./UsersSkillFindManyArgs";
import { UsersSkillFindUniqueArgs } from "./UsersSkillFindUniqueArgs";
import { UsersSkill } from "./UsersSkill";
import { Skill } from "../../skill/base/Skill";
import { User } from "../../user/base/User";
import { UsersSkillService } from "../usersSkill.service";

@graphql.Resolver(() => UsersSkill)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class UsersSkillResolverBase {
  constructor(
    protected readonly service: UsersSkillService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "UsersSkill",
    action: "read",
    possession: "any",
  })
  async _usersSkillsMeta(
    @graphql.Args() args: UsersSkillFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [UsersSkill])
  @nestAccessControl.UseRoles({
    resource: "UsersSkill",
    action: "read",
    possession: "any",
  })
  async usersSkills(
    @graphql.Args() args: UsersSkillFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<PaginatedInterface<UsersSkill>> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "UsersSkill",
    });
    const results = await this.service.findMany(args);
    const result = results.paginatedResult.map((result: UsersSkill) =>
      permission.filter(result)
    );
    return { paginatedResult: result, totalCount: results.totalCount };
  }

  @graphql.Query(() => UsersSkill, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "UsersSkill",
    action: "read",
    possession: "own",
  })
  async usersSkill(
    @graphql.Args() args: UsersSkillFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<UsersSkill | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "UsersSkill",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => UsersSkill)
  @nestAccessControl.UseRoles({
    resource: "UsersSkill",
    action: "create",
    possession: "any",
  })
  async createUsersSkill(
    @graphql.Args() args: CreateUsersSkillArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<UsersSkill> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "UsersSkill",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"UsersSkill"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        skill: args.data.skill
          ? {
              connect: args.data.skill,
            }
          : undefined,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => UsersSkill)
  @nestAccessControl.UseRoles({
    resource: "UsersSkill",
    action: "update",
    possession: "any",
  })
  async updateUsersSkill(
    @graphql.Args() args: UpdateUsersSkillArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<UsersSkill | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "UsersSkill",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"UsersSkill"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          skill: args.data.skill
            ? {
                connect: args.data.skill,
              }
            : undefined,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => UsersSkill)
  @nestAccessControl.UseRoles({
    resource: "UsersSkill",
    action: "delete",
    possession: "any",
  })
  async deleteUsersSkill(
    @graphql.Args() args: DeleteUsersSkillArgs
  ): Promise<UsersSkill | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Skill, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "UsersSkill",
    action: "read",
    possession: "any",
  })
  async skill(
    @graphql.Parent() parent: UsersSkill,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Skill | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Skill",
    });
    const result = await this.service.getSkill(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.ResolveField(() => User, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "UsersSkill",
    action: "read",
    possession: "any",
  })
  async user(
    @graphql.Parent() parent: UsersSkill,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<User | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "User",
    });
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
