/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { RecruiterWhereUniqueInput } from "./RecruiterWhereUniqueInput";
import { RecruiterUpdateInput } from "./RecruiterUpdateInput";

@ArgsType()
class UpdateRecruiterArgs {
  @Field(() => RecruiterWhereUniqueInput, { nullable: false })
  where!: RecruiterWhereUniqueInput;
  @Field(() => RecruiterUpdateInput, { nullable: false })
  data!: RecruiterUpdateInput;
}

export { UpdateRecruiterArgs };
