/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested , IsEnum, IsInt, IsNumber } from "class-validator";
import { CandidateWhereUniqueInput } from "../candidate/base/CandidateWhereUniqueInput";
import { Type } from "class-transformer";
import { RecruiterWhereUniqueInput } from "../recruiter/base/RecruiterWhereUniqueInput";
import { EnumUserSex } from "../auth/registerEnumType";
import { JobWhereUniqueInput } from "src/job/base/JobWhereUniqueInput";
import { ExperienceCreateInput } from "src/experience/base/ExperienceCreateInput";
import { CourseCreateInput } from "src/course/base/CourseCreateInput";
@InputType()
class UserProfileUpdateArgs {
//   @ApiProperty({
//     required: true,
//     type: String,
//   })
//   @IsString()
//   @Field(() => String)
//   id!: string;


  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string;


  @ApiProperty({
    required: false,
    type: [String],
  })
  @IsString({
    each: true,
  })
  @IsOptional()
  @Field(() => [String], {
    nullable: true,
  })
  roles?: Array<string>;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: false,
  })
  email!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phone?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  address?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumUserSex,
  })
  @IsEnum(EnumUserSex)
  @IsOptional()
  @Field(() => EnumUserSex, {
    nullable: false,
  })
  sex!: "Homme" | "Femme" ;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String)
  city?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String)
  kmRadius?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  jobName?: string | null;

}
export { UserProfileUpdateArgs};
