/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { SkillWhereInput } from "./SkillWhereInput";
import { Type } from "class-transformer";
import { SkillOrderByInput } from "./SkillOrderByInput";

@ArgsType()
class SkillFindManyArgs {
  @ApiProperty({
    required: false,
    type: () => SkillWhereInput,
  })
  @Field(() => SkillWhereInput, { nullable: true })
  @Type(() => SkillWhereInput)
  where?: SkillWhereInput;

  @ApiProperty({
    required: false,
    type: SkillOrderByInput,
  })
  @Field(() => SkillOrderByInput, { nullable: true })
  @Type(() => SkillOrderByInput)
  orderBy?: SkillOrderByInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { SkillFindManyArgs };
