/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested , IsEnum } from "class-validator";
import { CandidateWhereUniqueInput } from "../../candidate/base/CandidateWhereUniqueInput";
import { Type } from "class-transformer";
import { RecruiterWhereUniqueInput } from "../../recruiter/base/RecruiterWhereUniqueInput";
import { EnumUserSex } from "../../auth/registerEnumType";
import { CandidateUpdateInput } from "src/candidate/base/CandidateUpdateInput";
import { RecruiterUpdateInput } from "src/recruiter/base/RecruiterUpdateInput";
import { JobUpdateInput } from "src/job/base/JobUpdateInput";
@InputType()
class UserUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string;

  @ApiProperty({
    required: false,
    type: [String],
  })
  @IsString({
    each: true,
  })
  @IsOptional()
  @Field(() => [String], {
    nullable: true,
  })
  roles?: Array<string>;

  // @ApiProperty({
  //   required: false,
  //   type: () => CandidateWhereUniqueInput,
  // })
  // @ValidateNested()
  // @Type(() => CandidateWhereUniqueInput)
  // @IsOptional()
  // @Field(() => CandidateWhereUniqueInput, {
  //   nullable: true,
  // })
  // candidate?: CandidateWhereUniqueInput | null;

  // @ApiProperty({
  //   required: false,
  //   type: () => RecruiterWhereUniqueInput,
  // })
  // @ValidateNested()
  // @Type(() => RecruiterWhereUniqueInput)
  // @IsOptional()
  // @Field(() => RecruiterWhereUniqueInput, {
  //   nullable: true,
  // })
  // recruiter?: RecruiterWhereUniqueInput | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: false,
  })
  email!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phone?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  address?: string | null;

  @ApiProperty({
    required: true,
    enum: EnumUserSex,
  })
  @IsEnum(EnumUserSex)
  @IsOptional()
  @Field(() => EnumUserSex, {
    nullable: false,
  })
  sex!: "Homme" | "Femme" ;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String)
  city?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String)
  kmRadius?: string;

  @ApiProperty({
    required: false,
    type: () => CandidateUpdateInput
  })
  @IsOptional()
  candidate?: CandidateUpdateInput;

  @ApiProperty({
    required: false,
    type: () => RecruiterUpdateInput
  })
  @IsOptional()
  recruiter?: RecruiterUpdateInput;



  @ApiProperty({
    required: false,
    type: () => JobUpdateInput
  })
  @IsOptional()
  job?: JobUpdateInput;

}


export { UserUpdateInput };
