/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, IsNumber } from "class-validator";

@ObjectType()
class userListDTO {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @Field(() => String)
  userId!: string;

  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;

  @Field(() => [String])
  roles!: Array<string>;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phone!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  address!: string | null; 
  
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  photo!: string | null; 

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  wantedPost!: string | null; 

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  tags!: string | null; 

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  personalCv!: string | null; 

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  mediaLink!: string | null; 
 
  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  like!: Number | null;

  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  view!: Number | null;

  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  share!: Number | null;

  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  comment!: Number | null;

  @IsNumber()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  total_interactions!: Number | null;
}
export { userListDTO };
