/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { VideoWhereUniqueInput } from "./VideoWhereUniqueInput";
import { VideoUpdateInput } from "./VideoUpdateInput";

@ArgsType()
class UpdateVideoArgs {
  @Field(() => VideoWhereUniqueInput, { nullable: false })
  where!: VideoWhereUniqueInput;
  @Field(() => VideoUpdateInput, { nullable: false })
  data!: VideoUpdateInput;
}

export { UpdateVideoArgs };
