/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested } from "class-validator";
import { QuestionTypeWhereUniqueInput } from "../../questionType/base/QuestionTypeWhereUniqueInput";
import { Type } from "class-transformer";
import { OfferWhereUniqueInput } from "../../offer/base/OfferWhereUniqueInput";
import { VideoWhereUniqueInput } from "../../video/base/VideoWhereUniqueInput";
import { VideoUpdateInput } from "src/video/base/VideoUpdateInput";
@InputType()
class QuestionUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  id?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: () => QuestionTypeWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => QuestionTypeWhereUniqueInput)
  @IsOptional()
  @Field(() => QuestionTypeWhereUniqueInput, {
    nullable: true,
  })
  questionType?: QuestionTypeWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => OfferWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => OfferWhereUniqueInput)
  @IsOptional()
  @Field(() => OfferWhereUniqueInput, {
    nullable: true,
  })
  offer?: OfferWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => VideoUpdateInput,
  })
  @ValidateNested()
  @Type(() => VideoUpdateInput)
  @IsOptional()
  @Field(() => VideoUpdateInput, {
    nullable: true,
  })
  video?: VideoUpdateInput;
}
export { QuestionUpdateInput };
