/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsDate, IsOptional, ValidateNested } from "class-validator";
import { Type } from "class-transformer";
import { QuestionType } from "../../questionType/base/QuestionType";
import { Offer } from "../../offer/base/Offer";
import { Video } from "../../video/base/Video";
@ObjectType()
class Question {
  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  @IsOptional()
updatedAt?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description!: string | null;

  @ApiProperty({
    required: false,
    type: () => QuestionType,
  })
  @ValidateNested()
  @Type(() => QuestionType)
  @IsOptional()
  questionType?: QuestionType | null;

  @ApiProperty({
    required: false,
    type: () => Offer,
  })
  @ValidateNested()
  @Type(() => Offer)
  @IsOptional()
  offer?: Offer | null;

  @ApiProperty({
    required: false,
    type: () => Video,
  })
  @ValidateNested()
  @Type(() => Video)
  @IsOptional()
  video?: Video | null;
}
export { Question };
