/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { QuestionTypeWhereUniqueInput } from "../../questionType/base/QuestionTypeWhereUniqueInput";
import { OfferWhereUniqueInput } from "../../offer/base/OfferWhereUniqueInput";
import { VideoWhereUniqueInput } from "../../video/base/VideoWhereUniqueInput";
@InputType()
class QuestionWhereInput {
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  title?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  description?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => QuestionTypeWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => QuestionTypeWhereUniqueInput)
  @IsOptional()
  @Field(() => QuestionTypeWhereUniqueInput, {
    nullable: true,
  })
  questionType?: QuestionTypeWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => OfferWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => OfferWhereUniqueInput)
  @IsOptional()
  @Field(() => OfferWhereUniqueInput, {
    nullable: true,
  })
  offer?: OfferWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => VideoWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => VideoWhereUniqueInput)
  @IsOptional()
  @Field(() => VideoWhereUniqueInput, {
    nullable: true,
  })
  video?: VideoWhereUniqueInput;
}
export { QuestionWhereInput };
