/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestMorgan from "nest-morgan";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { PaginatedInterface } from "../../util/PaginatedInterface";
import { EventService } from "../event.service";
import { EventCreateInput } from "./EventCreateInput";
import { EventWhereInput } from "./EventWhereInput";
import { EventWhereUniqueInput } from "./EventWhereUniqueInput";
import { EventFindManyArgs } from "./EventFindManyArgs";
import { EventUpdateInput } from "./EventUpdateInput";
import { Event } from "./Event";
import { Post } from "../../post/base/Post";
import { getListEventDto } from "./getListEvent.dto";
@swagger.ApiBearerAuth()
export class EventControllerBase {
  constructor(
    protected readonly service: EventService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Post()
  @nestAccessControl.UseRoles({
    resource: "Event",
    action: "create",
    possession: "any",
  })
  @swagger.ApiCreatedResponse({ type: Event })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: EventCreateInput,
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<Event> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Event",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new errors.ForbiddenException(
        `providing the properties: ${properties} on ${"Event"} creation is forbidden for roles: ${roles}`
      );
    }
    return await this.service.create({
      data: {
        ...data,
        speakers:
          data.speakers && data.speakers.length > 0
            ? data.speakers.join(";")
            : "",
        publication: {
          create: {
            ...data.publication,
            type: "event",
            publicationsOnCommunities:
              data.publication.publicationsOnCommunities &&
              data.publication.publicationsOnCommunities.length > 0
                ? {
                    createMany: {
                      data: data.publication.publicationsOnCommunities.map(
                        (e) => {
                          return { communityId: e };
                        }
                      ),
                    },
                  }
                : undefined,
            user: data.publication.user
              ? {
                  connect: data.publication.user,
                }
              : undefined,
            offer: undefined,
            post: undefined,
            story: undefined,
            video: undefined,
          },
        },
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        location: true,
        file: true,
        link: true,
        startDate: true,

        publication: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Get()
  @nestAccessControl.UseRoles({
    resource: "Event",
    action: "read",
    possession: "any",
  })
  @swagger.ApiOkResponse({ type: getListEventDto })
  @swagger.ApiForbiddenResponse()
  @swagger.ApiQuery({
    type: () => EventFindManyArgs,
    style: "deepObject",
    explode: true,
  })
  async findMany(
    @common.Req() request: Request,
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<PaginatedInterface<Event>> {
    const args = plainToClass(EventFindManyArgs, request.query);

    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Event",
    });
    const results = await this.service.findMany({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        location: true,
        file: true,
        link: true,
        startDate: true,

        publication: {
          select: {
            id: true,
          },
        },
      },
    });
    const result = results.paginatedResult.map((result: Event) =>
      permission.filter(result)
    );
    return { paginatedResult: result, totalCount: results.totalCount };
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Get("/:id")
  @nestAccessControl.UseRoles({
    resource: "Event",
    action: "read",
    possession: "own",
  })
  @swagger.ApiOkResponse({ type: Event })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: EventWhereUniqueInput,
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<Event | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Event",
    });
    const result = await this.service.findOne({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        location: true,
        file: true,
        link: true,
        startDate: true,
        endDate: true,
        speakers: true,
        eventMode:true,
        publication: {
          select: {
            id: true,
            title: true,
            description: true,
            publicationsOnCommunities: {
              select: {
                communityId: true,
              },
            },
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return permission.filter(result);
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Patch("/:id")
  @nestAccessControl.UseRoles({
    resource: "Event",
    action: "update",
    possession: "any",
  })
  @swagger.ApiOkResponse({ type: Event })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: EventWhereUniqueInput,
    @common.Body()
    data: EventUpdateInput,
    @nestAccessControl.UserRoles() userRoles: string[]
  ): Promise<Event | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Event",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(permission, data);
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new errors.ForbiddenException(
        `providing the properties: ${properties} on ${"Event"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,
          speakers:
            data.speakers && data.speakers.length > 0
              ? data.speakers.join(";")
              : "",
          publication: data.publication
            ? {
                update: {
                  ...data.publication,
                  type: "event",
                  publicationsOnCommunities: data.publication
                    .publicationsOnCommunities
                    ? {
                        deleteMany: {
                          publicationId: data.publication.id,
                        },
                        createMany: {
                          data: data.publication.publicationsOnCommunities.map(
                            (e) => {
                              return { communityId: e };
                            }
                          ),
                        },
                      }
                    : undefined,

                  user: data.publication.user
                    ? {
                        connect: data.publication.user,
                      }
                    : undefined,
                  offer: undefined,
                  post: undefined,
                  story: undefined,
                  video: undefined,
                },
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          location: true,
          file: true,
          link: true,
          startDate: true,

          publication: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(nestMorgan.MorganInterceptor("combined"))
  @common.UseGuards(
    defaultAuthGuard.DefaultAuthGuard,
    nestAccessControl.ACGuard
  )
  @common.Delete("/:id")
  @nestAccessControl.UseRoles({
    resource: "Event",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiOkResponse({ type: Event })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: EventWhereUniqueInput
  ): Promise<Event | null> {
    try {
      return await this.service.delete({
        where: params,
        data: {
          deletedAt: new Date(),
          publication: {
            update: {
              deletedAt: new Date(),
              publicationsOnCommunities: {
                updateMany: { data: { deletedAt: new Date() }, where: {} },
              },
              socialinterractions:{
                updateMany:{
                  data:{deletedAt:new Date()},where:{}
                }
              }
            },
          },
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          location: true,
          file: true,
          link: true,
          startDate: true,

          publication: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
