/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { PrismaService } from "nestjs-prisma";
import { Prisma, Comment, User } from "@prisma/client";
import { PaginatedInterface } from "../../util/PaginatedInterface";
import { DbService } from "src/dbService/db.service";

export class CommentServiceBase {
  constructor(protected readonly prisma: DbService) {}

  async count<T extends Prisma.CommentFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.CommentFindManyArgs>
  ): Promise<number> {
    return this.prisma.comment.count(args);
  }

  async findMany<T extends Prisma.CommentFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.CommentFindManyArgs>
  ): Promise<PaginatedInterface<Comment>> {
    const [data, totalCount] = await Promise.all([
      this.prisma.comment.findMany(args),
      this.prisma.comment.count(),
    ]);

    return { paginatedResult: data, totalCount };
  }
  async findOne<T extends Prisma.CommentFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.CommentFindUniqueArgs>
  ): Promise<Comment | null> {
    return this.prisma.comment.findUnique(args);
  }
  async create<T extends Prisma.CommentCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.CommentCreateArgs>
  ): Promise<Comment> {
    return this.prisma.comment.create<T>(args);
  }
  async update<T extends Prisma.CommentUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.CommentUpdateArgs>
  ): Promise<Comment> {
    return this.prisma.comment.update<T>(args);
  }
  async delete<T extends Prisma.CommentDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.CommentDeleteArgs>
  ): Promise<Comment> {
    return this.prisma.comment.delete(args);
  }

  async getUser(parentId: string): Promise<User | null> {
    return this.prisma.comment
      .findUnique({
        where: { id: parentId },
      })
      .user();
  }
}
